# Generated by Django 4.2.7 on 2024-01-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0003_alter_card_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="definition",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
