# Generated by Django 4.2.7 on 2024-01-13 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0004_card_definition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added",
                        to="flashcards.set",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
